server:
  port: 9090

zzweather:
  source: "WeatherBit"
  locations:
    - "Sydney"
    - "Melbourne"
    - "Wollongong"

provider:
  name: "WeatherBit"
  country: "AU"
  url: "https://api.weatherbit.io/v2.0/current"
  key: "212a258a95b84252bedc97d973b97bbf"
  postcodes:
    - "Sydney-2000"
    - "Melbourne-3000"
    - "Wollongong-2500"